apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nexa.fullname" . }}-pooler
  labels:
    {{- include "nexa.labels" . | nindent 4 }}
data:
  pooler.exs: |-
{{ .Files.Get "files/pooler/pooler.exs" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nexa.fullname" . }}-functions-main
  labels:
    {{- include "nexa.labels" . | nindent 4 }}
data:
  index.ts: |-
{{ .Files.Get "files/functions/main/index.ts" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nexa.fullname" . }}-functions-hello
  labels:
    {{- include "nexa.labels" . | nindent 4 }}
data:
  index.ts: |-
{{ .Files.Get "files/functions/hello/index.ts" | indent 4 }}
