apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nexa.fullname" . }}-kong
  labels:
    {{- include "nexa.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.kong }}
  selector:
    matchLabels:
      {{- include "nexa.selectorLabels" (dict "component" "kong") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nexa.selectorLabels" (dict "component" "kong") | nindent 8 }}
      annotations:
        {{- include "nexa.podAnnotations" . | nindent 8 }}
    spec:
      containers:
        - name: kong
          image: "{{ .Values.images.kong.repository }}:{{ .Values.images.kong.tag }}"
          command: ["/bin/sh", "/home/kong/kong-entrypoint.sh"]
          {{- include "nexa.envFrom" . | nindent 10 }}
          env:
            - { name: KONG_DATABASE, value: "off" }
            - { name: KONG_DECLARATIVE_CONFIG, value: /usr/local/kong/kong.yml }
            - { name: KONG_ROUTER_FLAVOR, value: expressions }
            - { name: KONG_DNS_ORDER, value: "LAST,A,CNAME" }
            - { name: KONG_DNS_NOT_FOUND_TTL, value: "1" }
            - { name: KONG_DNS_VALID_TTL, value: "5" }
            - { name: KONG_PLUGINS, value: "request-transformer,cors,key-auth,acl,basic-auth,request-termination,ip-restriction,post-function" }
            - { name: KONG_NGINX_PROXY_PROXY_BUFFER_SIZE, value: 160k }
            - { name: KONG_NGINX_PROXY_PROXY_BUFFERS, value: "64 160k" }
            - { name: KONG_PROXY_ACCESS_LOG, value: "/dev/stdout combined" }
            - name: SUPABASE_ANON_KEY
              valueFrom: { secretKeyRef: { name: {{ include "nexa.fullname" . }}-secrets, key: ANON_KEY } }
            - name: SUPABASE_SERVICE_KEY
              valueFrom: { secretKeyRef: { name: {{ include "nexa.fullname" . }}-secrets, key: SERVICE_ROLE_KEY } }
          ports:
            - containerPort: 8000
            - containerPort: 8443
          readinessProbe:
            exec: { command: ["kong", "health"] }
            periodSeconds: 5
          livenessProbe:
            exec: { command: ["kong", "health"] }
            periodSeconds: 10
            initialDelaySeconds: 10
          volumeMounts:
            - { name: kong-config, mountPath: /home/kong/temp.yml, subPath: kong.yml }
            - { name: kong-config, mountPath: /home/kong/kong-entrypoint.sh, subPath: kong-entrypoint.sh }
          resources:
            {{- toYaml .Values.resources.medium | nindent 12 }}
      volumes:
        - name: kong-config
          configMap: { name: {{ include "nexa.fullname" . }}-kong }
---
apiVersion: v1
kind: Service
metadata:
  name: kong
  labels:
    {{- include "nexa.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "nexa.selectorLabels" (dict "component" "kong") | nindent 4 }}
  ports:
    - { name: http, port: 8000, targetPort: 8000 }
    - { name: https, port: 8443, targetPort: 8443 }
