# Generated by Django 5.2.7 on 2026-08-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PortalUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "is_admin",
                    models.BooleanField(
                        default=False,
                        help_text="Can manage other users' roles (via the portal's /admin/users and the DRF API). Not editable through the API - grant it here only.",
                    ),
                ),
                (
                    "dbadmin",
                    models.BooleanField(
                        default=False,
                        help_text="Automatic (no extra login) access to the 'Data Model' tile / Supabase Studio.",
                    ),
                ),
                (
                    "dashboardadmin",
                    models.BooleanField(
                        default=False,
                        help_text="Edit access in Metabase. Everyone else gets read-only access.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="StudioCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(default="supabase", max_length=150)),
                ("password", models.CharField(blank=True, max_length=150)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
